[repository]


[repository.documentation]
standards = ["readme", "vision", "philosophy", "architecture", "feature", "feature-design", "feature-technical", "design", "engineering", "external-context", "prototype"]

[compilation]
watch = false

[audit]
default-severity = "suggestion"

[output]
format = "text"
